services:
  app_proxy:
    environment:
      APP_HOST: neutralis-pools_server_1
      APP_PORT: 8788

  server:
    image: ghcr.io/rhstuff01/neutralis-pools:1.0.4
    restart: on-failure
    stop_grace_period: 15s
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      PORT: "8788"
      NEUTRALIS_POOLS_DATA_DIR: /data
      SYNC_CHECK_SECONDS: "60"
    read_only: true
    tmpfs:
      - /tmp:size=16m,noexec,nosuid
    security_opt:
      - no-new-privileges:true
